export const ACCOUNT_REGISTER_REQUEST = "ACCOUNT_REGISTER_REQUEST";
export const ACCOUNT_REGISTER_SUCCESS = "ACCOUNT_REGISTER_SUCCESS";
export const ACCOUNT_REGISTER_FAIL = "ACCOUNT_REGISTER_FAIL";

export const ACCOUNT_UPDATE_REQUEST = "ACCOUNT_UPDATE_REQUEST";
export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_UPDATE_SUCCESS";
export const ACCOUNT_UPDATE_FAIL = "ACCOUNT_UPDATE_FAIL";

export const ACCOUNT_DETAILS_REQUEST = "ACCOUNT_DETAILS_REQUEST";
export const ACCOUNT_DETAILS_SUCCESS = "ACCOUNT_DETAILS_SUCCESS";
export const ACCOUNT_DETAILS_FAIL = "ACCOUNT_DETAILS_FAIL";

export const ACCOUNT_DETAILS_PENDING_REQUEST =
  "ACCOUNT_DETAILS_PENDING_REQUEST";
export const ACCOUNT_DETAILS_PENDING_SUCCESS =
  "ACCOUNT_DETAILS_PENDING_SUCCESS";
export const ACCOUNT_DETAILS_PENDING_FAIL = "ACCOUNT_DETAILS_PENDING_FAIL";

export const ACCOUNT_APPROVE_FAIL = "ACCOUNT_APPROVE_FAIL";
export const ACCOUNT_APPROVE_REQUEST = "ACCOUNT_APPROVE_REQUEST";
export const ACCOUNT_APPROVE_SUCCESS = "ACCOUNT_APPROVE_SUCCESS";
export const ACCOUNT_APPROVE_CLEAR = "ACCOUNT_APPROVE_CLEAR";

export const ACCOUNT_PIN_UPDATE_FAIL = "ACCOUNT_PIN_UPDATE_FAIL";
export const ACCOUNT_PIN_UPDATE_REQUEST = "ACCOUNT_PIN_UPDATE_REQUEST";
export const ACCOUNT_PIN_UPDATE_SUCCESS = "ACCOUNT_PIN_UPDATE_SUCCESS";
export const ACCOUNT_PIN_UPDATE_CLEAR = "ACCOUNT_PIN_UPDATE_CLEAR";
