export const TRANSACTION_DEPOSIT_REQUEST = "TRANSACTION_DEPOSIT_REQUEST";
export const TRANSACTION_DEPOSIT_SUCCESS = "TRANSACTION_DEPOSIT_SUCCESS";
export const TRANSACTION_DEPOSIT_FAIL = "TRANSACTION_DEPOSIT_FAIL";
export const CLEAR_TRANSACTION_DEPOSIT_REQUEST =
  "CLEAR_TRANSACTION_DEPOSIT_REQUEST";

export const TRANSACTION_WITHDRAWL_REQUEST = "TRANSACTION_WITHDRAWL_REQUEST";
export const TRANSACTION_WITHDRAWL_SUCCESS = "TRANSACTION_WITHDRAWL_SUCCESS";
export const TRANSACTION_WITHDRAWL_FAIL = "TRANSACTION_WITHDRAWL_FAIL";
export const CLEAR_TRANSACTION_WITHDRAWL_REQUEST =
  "CLEAR_TRANSACTION_WITHDRAWL_REQUEST";

export const TRANSACTION_LIST_REQUEST = "TRANSACTION_LIST_REQUEST";
export const TRANSACTION_LIST_SUCCESS = "TRANSACTION_LIST_SUCCESS";
export const TRANSACTION_LIST_FAIL = "TRANSACTION_LIST_FAIL";
